### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [MarianoGirbau/JuegaFulbo-Back#1]
Buenas! como va? encontre algunos comentarios en el codigo,
![image](https://github.com/MarianoGirbau/JuegaFulbo-Back/assets/53904695/0d0ca56c-6375-4a8d-a053-9172177ef6fa)
Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Aron9377** [comment]
Buenos dias Nico , correcciones realizadas! Saludos !
